### ISSUE TITLE
Bug: ColumnMap for property "usergroup" of class "In2code\Luxletter\Domain\Model\User" is missing

### ISSUE THREAD

**Issue by rr-it** [in2code-de/luxletter#62]
In **TYPO3 9** Backend I get this error on switching from the luxletter "Dashboard" tab to the "Newsletter" tab:

~~~
Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1355142232:
The ColumnMap for property "usergroup" of class "In2code\Luxletter\Domain\Model\User" is missing.

TYPO3\CMS\Extbase\Persistence\Generic\Exception\MissingColumnMapException thrown in file /home/example/html/public/typo3/sysext/extbase/Classes/Persistence/Generic/Storage/Typo3DbQueryParser.php in line 1098.
Requested URL: https://www.example.org/typo3/index.php?route=%%2Flux%%2FLuxletterLuxletter%%2F&token=--AnonymizedToken--&tx_luxletter_lux_luxletterluxletter%%5Baction%%5D=list&tx_luxletter_lux_luxletterluxletter%%5Bcontroller%%5D=Newsletter 
~~~

### How to reproduce
1. "Flush cache" via TYPO3-maintenance
2. Open newsletter-link https://www.example.org/?luxletterlink=9b4dd70e4fa252152403abd19ac5923abb0f437aa00f91cdf0444aa34017b670
3. Open luxletter submodule in Backend and switch from the luxletter "Dashboard" tab to the "Newsletter" tab

### Workaround
1. "Flush cache" via TYPO3-maintenance
2. First: Open luxletter submodule in Backend and switch from the luxletter "Dashboard" tab to the "Newsletter" tab
3. Then: Open newsletter-link https://www.example.org/?luxletterlink=9b4dd70e4fa252152403abd19ac5923abb0f437aa00f91cdf0444aa34017b670
4. The "Newsletter" tab in luxletter submodule still works.

### System
- luxletter: 2.3.0 - with extra DB views to circumvent persistence problem https://github.com/in2code-de/luxletter/issues/30#issuecomment-710189102
- TYPO3-Version: 9.5.22
- Webserver: Apache
- PHP-Version: 7.3.21
- Database (Default): MySQL 5.5.5-10.0.38-MariaDB
- Application Context: Production
- Composer Mode: active
- Operating System: Linux 3.10.0-693.11.6.el7.x86_64

**Comment by rr-it** [comment]
Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1355142232:
The ColumnMap for property "usergroup" of class "In2code\Luxletter\Domain\Model\User" is missing.

<details>
  <summary>Full stack trace</summary>

~~~ php
TYPO3\CMS\Extbase\Persistence\Generic\Exception\MissingColumnMapException thrown in file /home/example/html/public/typo3/sysext/extbase/Classes/Persistence/Generic/Storage/Typo3DbQueryParser.php in line 1098.
Requested URL: https://www.example.org/typo3/index.php?route=%2Flux%2FLuxletterLuxletter%2F&token=--AnonymizedToken--&tx_luxletter_lux_luxletterluxletter%5Baction%5D=list&tx_luxletter_lux_luxletterluxletter%5Bcontroller%5D=Newsletter

TYPO3\CMS\Extbase\Persistence\Generic\Exception\MissingColumnMapException: The ColumnMap for property "usergroup" of class "In2code\Luxletter\Domain\Model\User" is missing. in /home/example/html/public/typo3/sysext/extbase/Classes/Persistence/Generic/Storage/Typo3DbQueryParser.php:1098

Stack trace:
#0 /home/example/html/public/typo3/sysext/extbase/Classes/Persistence/Generic/Storage/Typo3DbQueryParser.php(599): TYPO3\CMS\Extbase\Persistence\Generic\Storage\Typo3DbQueryParser->addUnionStatement('In2code\\Luxlett...', 'tx_luxletter_do...', 'usergroup.uid', '')
#1 /home/example/html/public/typo3/sysext/extbase/Classes/Persistence/Generic/Storage/Typo3DbQueryParser.php(453): TYPO3\CMS\Extbase\Persistence\Generic\Storage\Typo3DbQueryParser->parseOperand(Object(TYPO3\CMS\Extbase\Persistence\Generic\Qom\PropertyValue), Object(TYPO3\CMS\Extbase\Persistence\Generic\Qom\Selector))
#2 /home/example/html/public/typo3/sysext/extbase/Classes/Persistence/Generic/Storage/Typo3DbQueryParser.php(438): TYPO3\CMS\Extbase\Persistence\Generic\Storage\Typo3DbQueryParser->parseDynamicOperand(Object(TYPO3\CMS\Extbase\Persistence\Generic\Qom\Comparison), Object(TYPO3\CMS\Extbase\Persistence\Generic\Qom\Selector))
#3 /home/example/html/public/typo3/sysext/extbase/Classes/Persistence/Generic/Storage/Typo3DbQueryParser.php(278): TYPO3\CMS\Extbase\Persistence\Generic\Storage\Typo3DbQueryParser->parseComparison(Object(TYPO3\CMS\Extbase\Persistence\Generic\Qom\Comparison), Object(TYPO3\CMS\Extbase\Persistence\Generic\Qom\Selector))
#4 /home/example/html/public/typo3/sysext/extbase/Classes/Persistence/Generic/Storage/Typo3DbQueryParser.php(186): TYPO3\CMS\Extbase\Persistence\Generic\Storage\Typo3DbQueryParser->parseConstraint(Object(TYPO3\CMS\Extbase\Persistence\Generic\Qom\Comparison), Object(TYPO3\CMS\Extbase\Persistence\Generic\Qom\Selector))
#5 /home/example/html/public/typo3/sysext/extbase/Classes/Persistence/Generic/Storage/Typo3DbBackend.php(456): TYPO3\CMS\Extbase\Persistence\Generic\Storage\Typo3DbQueryParser->convertQueryToDoctrineQueryBuilder(Object(TYPO3\CMS\Extbase\Persistence\Generic\Query))
#6 /home/example/html/public/typo3/sysext/extbase/Classes/Persistence/Generic/Backend.php(207): TYPO3\CMS\Extbase\Persistence\Generic\Storage\Typo3DbBackend->getObjectCountByQuery(Object(TYPO3\CMS\Extbase\Persistence\Generic\Query))
#7 /home/example/html/public/typo3/sysext/extbase/Classes/Persistence/Generic/PersistenceManager.php(116): TYPO3\CMS\Extbase\Persistence\Generic\Backend->getObjectCountByQuery(Object(TYPO3\CMS\Extbase\Persistence\Generic\Query))
#8 /home/example/html/public/typo3/sysext/extbase/Classes/Persistence/Generic/QueryResult.php(143): TYPO3\CMS\Extbase\Persistence\Generic\PersistenceManager->getObjectCountByQuery(Object(TYPO3\CMS\Extbase\Persistence\Generic\Query))
#9 /home/example/html/public/typo3conf/ext/luxletter/Classes/ViewHelpers/Usergroup/GetNumberOfReceiversFromGroupViewHelper.php(32): TYPO3\CMS\Extbase\Persistence\Generic\QueryResult->count()
#10 [internal function]: In2code\Luxletter\ViewHelpers\Usergroup\GetNumberOfReceiversFromGroupViewHelper->render()
#11 /home/example/html/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php(262): call_user_func(Array)
#12 /home/example/html/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php(250): TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper->callRenderMethod()
#13 /home/example/html/vendor/typo3fluid/fluid/src/Core/ViewHelper/ViewHelperInvoker.php(79): TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper->initializeArgumentsAndRender()
#14 /home/example/html/vendor/typo3fluid/fluid/src/Core/Parser/SyntaxTree/ViewHelperNode.php(153): TYPO3Fluid\Fluid\Core\ViewHelper\ViewHelperInvoker->invoke(Object(In2code\Luxletter\ViewHelpers\Usergroup\GetNumberOfReceiversFromGroupViewHelper), Array, Object(TYPO3\CMS\Fluid\Core\Rendering\RenderingContext))
#15 /home/example/html/vendor/typo3fluid/fluid/src/Core/Parser/SyntaxTree/EscapingNode.php(43): TYPO3Fluid\Fluid\Core\Parser\SyntaxTree\ViewHelperNode->evaluate(Object(TYPO3\CMS\Fluid\Core\Rendering\RenderingContext))
#16 /home/example/html/vendor/typo3fluid/fluid/src/Core/Parser/SyntaxTree/AbstractNode.php(56): TYPO3Fluid\Fluid\Core\Parser\SyntaxTree\EscapingNode->evaluate(Object(TYPO3\CMS\Fluid\Core\Rendering\RenderingContext))
#17 /home/example/html/vendor/typo3fluid/fluid/src/Core/Parser/SyntaxTree/AbstractNode.php(36): TYPO3Fluid\Fluid\Core\Parser\SyntaxTree\AbstractNode->evaluateChildNode(Object(TYPO3Fluid\Fluid\Core\Parser\SyntaxTree\EscapingNode), Object(TYPO3\CMS\Fluid\Core\Rendering\RenderingContext), false)
#18 /home/example/html/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php(304): TYPO3Fluid\Fluid\Core\Parser\SyntaxTree\AbstractNode->evaluateChildNodes(Object(TYPO3\CMS\Fluid\Core\Rendering\RenderingContext))
#19 /home/example/html/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php(319): TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper->renderChildren()
#20 /home/example/html/vendor/typo3fluid/fluid/src/ViewHelpers/ForViewHelper.php(133): TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper->TYPO3Fluid\Fluid\Core\ViewHelper\{closure}()
#21 /home/example/html/vendor/typo3fluid/fluid/src/Core/ViewHelper/Traits/CompileWithRenderStatic.php(30): TYPO3Fluid\Fluid\ViewHelpers\ForViewHelper::renderStatic(Array, Object(Closure), Object(TYPO3\CMS\Fluid\Core\Rendering\RenderingContext))
#22 [internal function]: TYPO3Fluid\Fluid\ViewHelpers\ForViewHelper->render()
#23 /home/example/html/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php(262): call_user_func(Array)
#24 /home/example/html/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php(250): TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper->callRenderMethod()
#25 /home/example/html/vendor/typo3fluid/fluid/src/Core/ViewHelper/ViewHelperInvoker.php(79): TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper->initializeArgumentsAndRender()
#26 /home/example/html/vendor/typo3fluid/fluid/src/Core/Parser/SyntaxTree/ViewHelperNode.php(153): TYPO3Fluid\Fluid\Core\ViewHelper\ViewHelperInvoker->invoke(Object(TYPO3Fluid\Fluid\ViewHelpers\ForViewHelper), Array, Object(TYPO3\CMS\Fluid\Core\Rendering\RenderingContext))
#27 /home/example/html/vendor/typo3fluid/fluid/src/Core/Parser/SyntaxTree/AbstractNode.php(56): TYPO3Fluid\Fluid\Core\Parser\SyntaxTree\ViewHelperNode->evaluate(Object(TYPO3\CMS\Fluid\Core\Rendering\RenderingContext))
#28 /home/example/html/vendor/typo3fluid/fluid/src/Core/Parser/SyntaxTree/AbstractNode.php(36): TYPO3Fluid\Fluid\Core\Parser\SyntaxTree\AbstractNode->evaluateChildNode(Object(TYPO3Fluid\Fluid\Core\Parser\SyntaxTree\ViewHelperNode), Object(TYPO3\CMS\Fluid\Core\Rendering\RenderingContext), false)
#29 /home/example/html/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php(304): TYPO3Fluid\Fluid\Core\Parser\SyntaxTree\AbstractNode->evaluateChildNodes(Object(TYPO3\CMS\Fluid\Core\Rendering\RenderingContext))
#30 /home/example/html/vendor/typo3fluid/fluid/src/ViewHelpers/ThenViewHelper.php(35): TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper->renderChildren()
#31 [internal function]: TYPO3Fluid\Fluid\ViewHelpers\ThenViewHelper->render()
#32 /home/example/html/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php(262): call_user_func(Array)
#33 /home/example/html/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php(250): TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper->callRenderMethod()
#34 /home/example/html/vendor/typo3fluid/fluid/src/Core/ViewHelper/ViewHelperInvoker.php(79): TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper->initializeArgumentsAndRender()
#35 /home/example/html/vendor/typo3fluid/fluid/src/Core/Parser/SyntaxTree/ViewHelperNode.php(153): TYPO3Fluid\Fluid\Core\ViewHelper\ViewHelperInvoker->invoke(Object(TYPO3Fluid\Fluid\ViewHelpers\ThenViewHelper), Array, Object(TYPO3\CMS\Fluid\Core\Rendering\RenderingContext))
#36 /home/example/html/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractConditionViewHelper.php(164): TYPO3Fluid\Fluid\Core\Parser\SyntaxTree\ViewHelperNode->evaluate(Object(TYPO3\CMS\Fluid\Core\Rendering\RenderingContext))
#37 /home/example/html/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractConditionViewHelper.php(60): TYPO3Fluid\Fluid\Core\ViewHelper\AbstractConditionViewHelper->renderThenChild()
#38 [internal function]: TYPO3Fluid\Fluid\Core\ViewHelper\AbstractConditionViewHelper->render()
#39 /home/example/html/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php(262): call_user_func(Array)
#40 /home/example/html/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php(250): TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper->callRenderMethod()
#41 /home/example/html/vendor/typo3fluid/fluid/src/Core/ViewHelper/ViewHelperInvoker.php(79): TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper->initializeArgumentsAndRender()
#42 /home/example/html/vendor/typo3fluid/fluid/src/Core/Parser/SyntaxTree/ViewHelperNode.php(153): TYPO3Fluid\Fluid\Core\ViewHelper\ViewHelperInvoker->invoke(Object(TYPO3Fluid\Fluid\ViewHelpers\IfViewHelper), Array, Object(TYPO3\CMS\Fluid\Core\Rendering\RenderingContext))
#43 /home/example/html/vendor/typo3fluid/fluid/src/Core/Parser/SyntaxTree/AbstractNode.php(56): TYPO3Fluid\Fluid\Core\Parser\SyntaxTree\ViewHelperNode->evaluate(Object(TYPO3\CMS\Fluid\Core\Rendering\RenderingContext))
#44 /home/example/html/vendor/typo3fluid/fluid/src/Core/Parser/SyntaxTree/AbstractNode.php(36): TYPO3Fluid\Fluid\Core\Parser\SyntaxTree\AbstractNode->evaluateChildNode(Object(TYPO3Fluid\Fluid\Core\Parser\SyntaxTree\ViewHelperNode), Object(TYPO3\CMS\Fluid\Core\Rendering\RenderingContext), false)
#45 /home/example/html/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php(304): TYPO3Fluid\Fluid\Core\Parser\SyntaxTree\AbstractNode->evaluateChildNodes(Object(TYPO3\CMS\Fluid\Core\Rendering\RenderingContext))
#46 /home/example/html/vendor/typo3fluid/fluid/src/ViewHelpers/SectionViewHelper.php(108): TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper->renderChildren()
#47 [internal function]: TYPO3Fluid\Fluid\ViewHelpers\SectionViewHelper->render()
#48 /home/example/html/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php(262): call_user_func(Array)
#49 /home/example/html/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php(250): TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper->callRenderMethod()
#50 /home/example/html/vendor/typo3fluid/fluid/src/Core/ViewHelper/ViewHelperInvoker.php(79): TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper->initializeArgumentsAndRender()
#51 /home/example/html/vendor/typo3fluid/fluid/src/Core/Parser/SyntaxTree/ViewHelperNode.php(153): TYPO3Fluid\Fluid\Core\ViewHelper\ViewHelperInvoker->invoke(Object(TYPO3Fluid\Fluid\ViewHelpers\SectionViewHelper), Array, Object(TYPO3\CMS\Fluid\Core\Rendering\RenderingContext))
#52 /home/example/html/vendor/typo3fluid/fluid/src/View/AbstractTemplateView.php(282): TYPO3Fluid\Fluid\Core\Parser\SyntaxTree\ViewHelperNode->evaluate(Object(TYPO3\CMS\Fluid\Core\Rendering\RenderingContext))
#53 /home/example/html/vendor/typo3fluid/fluid/src/ViewHelpers/RenderViewHelper.php(143): TYPO3Fluid\Fluid\View\AbstractTemplateView->renderSection('content', Array, false)
#54 /home/example/html/var/cache/code/fluid_template/layout_Backend_html_b6105318cee2608ef343e9f7bc25543016c40920.php(370): TYPO3Fluid\Fluid\ViewHelpers\RenderViewHelper::renderStatic(Array, Object(Closure), Object(TYPO3\CMS\Fluid\Core\Rendering\RenderingContext))
#55 /home/example/html/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php(302): layout_Backend_html_b6105318cee2608ef343e9f7bc25543016c40920->{closure}()
#56 /home/example/html/public/typo3/sysext/fluid/Classes/ViewHelpers/Be/ContainerViewHelper.php(115): TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper->renderChildren()
#57 [internal function]: TYPO3\CMS\Fluid\ViewHelpers\Be\ContainerViewHelper->render()
#58 /home/example/html/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php(262): call_user_func(Array)
#59 /home/example/html/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php(250): TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper->callRenderMethod()
#60 /home/example/html/vendor/typo3fluid/fluid/src/Core/ViewHelper/ViewHelperInvoker.php(79): TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper->initializeArgumentsAndRender()
#61 /home/example/html/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php(522): TYPO3Fluid\Fluid\Core\ViewHelper\ViewHelperInvoker->invoke('TYPO3\\CMS\\Fluid...', Array, Object(TYPO3\CMS\Fluid\Core\Rendering\RenderingContext), Object(Closure))
#62 /home/example/html/var/cache/code/fluid_template/layout_Backend_html_b6105318cee2608ef343e9f7bc25543016c40920.php(404): TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper::renderStatic(Array, Object(Closure), Object(TYPO3\CMS\Fluid\Core\Rendering\RenderingContext))
#63 /home/example/html/vendor/typo3fluid/fluid/src/View/AbstractTemplateView.php(201): layout_Backend_html_b6105318cee2608ef343e9f7bc25543016c40920->render(Object(TYPO3\CMS\Fluid\Core\Rendering\RenderingContext))
#64 /home/example/html/public/typo3/sysext/extbase/Classes/Mvc/Controller/ActionController.php(324): TYPO3Fluid\Fluid\View\AbstractTemplateView->render()
#65 /home/example/html/public/typo3/sysext/extbase/Classes/Mvc/Controller/ActionController.php(167): TYPO3\CMS\Extbase\Mvc\Controller\ActionController->callActionMethod()
#66 /home/example/html/public/typo3/sysext/extbase/Classes/Mvc/Dispatcher.php(73): TYPO3\CMS\Extbase\Mvc\Controller\ActionController->processRequest(Object(TYPO3\CMS\Extbase\Mvc\Web\Request), Object(TYPO3\CMS\Extbase\Mvc\Web\Response))
#67 /home/example/html/public/typo3/sysext/extbase/Classes/Mvc/Web/BackendRequestHandler.php(35): TYPO3\CMS\Extbase\Mvc\Dispatcher->dispatch(Object(TYPO3\CMS\Extbase\Mvc\Web\Request), Object(TYPO3\CMS\Extbase\Mvc\Web\Response))
#68 /home/example/html/public/typo3/sysext/extbase/Classes/Core/Bootstrap.php(217): TYPO3\CMS\Extbase\Mvc\Web\BackendRequestHandler->handleRequest()
#69 [internal function]: TYPO3\CMS\Extbase\Core\Bootstrap->handleBackendRequest(Object(TYPO3\CMS\Core\Http\ServerRequest))
#70 /home/example/html/public/typo3/sysext/backend/Classes/Http/RouteDispatcher.php(93): call_user_func_array(Array, Array)
#71 /home/example/html/public/typo3/sysext/backend/Classes/Http/RequestHandler.php(73): TYPO3\CMS\Backend\Http\RouteDispatcher->dispatch(Object(TYPO3\CMS\Core\Http\ServerRequest), Object(TYPO3\CMS\Core\Http\Response))
#72 /home/example/html/public/typo3/sysext/backend/Classes/Middleware/SiteResolver.php(59): TYPO3\CMS\Backend\Http\RequestHandler->handle(Object(TYPO3\CMS\Core\Http\ServerRequest))
#73 /home/example/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\CMS\Backend\Middleware\SiteResolver->process(Object(TYPO3\CMS\Core\Http\ServerRequest), Object(TYPO3\CMS\Backend\Http\RequestHandler))
#74 /home/example/html/public/typo3/sysext/backend/Classes/Middleware/AdditionalResponseHeaders.php(39): class@anonymous->handle(Object(TYPO3\CMS\Core\Http\ServerRequest))
#75 /home/example/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\CMS\Backend\Middleware\AdditionalResponseHeaders->process(Object(TYPO3\CMS\Core\Http\ServerRequest), Object(class@anonymous))
#76 /home/example/html/public/typo3/sysext/backend/Classes/Middleware/OutputCompression.php(45): class@anonymous->handle(Object(TYPO3\CMS\Core\Http\ServerRequest))
#77 /home/example/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\CMS\Backend\Middleware\OutputCompression->process(Object(TYPO3\CMS\Core\Http\ServerRequest), Object(class@anonymous))
#78 /home/example/html/public/typo3/sysext/backend/Classes/Middleware/LegacyBackendTemplateInitialization.php(42): class@anonymous->handle(Object(TYPO3\CMS\Core\Http\ServerRequest))
#79 /home/example/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\CMS\Backend\Middleware\LegacyBackendTemplateInitialization->process(Object(TYPO3\CMS\Core\Http\ServerRequest), Object(class@anonymous))
#80 /home/example/html/public/typo3/sysext/backend/Classes/Middleware/BackendUserAuthenticator.php(70): class@anonymous->handle(Object(TYPO3\CMS\Core\Http\ServerRequest))
#81 /home/example/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\CMS\Backend\Middleware\BackendUserAuthenticator->process(Object(TYPO3\CMS\Core\Http\ServerRequest), Object(class@anonymous))
#82 /home/example/html/public/typo3/sysext/backend/Classes/Middleware/BackendRouteInitialization.php(73): class@anonymous->handle(Object(TYPO3\CMS\Core\Http\ServerRequest))
#83 /home/example/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\CMS\Backend\Middleware\BackendRouteInitialization->process(Object(TYPO3\CMS\Core\Http\ServerRequest), Object(class@anonymous))
#84 /home/example/html/public/typo3/sysext/backend/Classes/Middleware/ForcedHttpsBackendRedirector.php(53): class@anonymous->handle(Object(TYPO3\CMS\Core\Http\ServerRequest))
#85 /home/example/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\CMS\Backend\Middleware\ForcedHttpsBackendRedirector->process(Object(TYPO3\CMS\Core\Http\ServerRequest), Object(class@anonymous))
#86 /home/example/html/public/typo3/sysext/backend/Classes/Middleware/LockedBackendGuard.php(71): class@anonymous->handle(Object(TYPO3\CMS\Core\Http\ServerRequest))
#87 /home/example/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\CMS\Backend\Middleware\LockedBackendGuard->process(Object(TYPO3\CMS\Core\Http\ServerRequest), Object(class@anonymous))
#88 /home/example/html/public/typo3/sysext/core/Classes/Middleware/NormalizedParamsAttribute.php(58): class@anonymous->handle(Object(TYPO3\CMS\Core\Http\ServerRequest))
#89 /home/example/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\CMS\Core\Middleware\NormalizedParamsAttribute->process(Object(TYPO3\CMS\Core\Http\ServerRequest), Object(class@anonymous))
#90 /home/example/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(67): class@anonymous->handle(Object(TYPO3\CMS\Core\Http\ServerRequest))
#91 /home/example/html/public/typo3/sysext/core/Classes/Http/AbstractApplication.php(108): TYPO3\CMS\Core\Http\MiddlewareDispatcher->handle(Object(TYPO3\CMS\Core\Http\ServerRequest))
#92 /home/example/html/public/typo3/sysext/backend/Classes/Http/Application.php(68): TYPO3\CMS\Core\Http\AbstractApplication->handle(Object(TYPO3\CMS\Core\Http\ServerRequest))
#93 /home/example/html/public/typo3/sysext/core/Classes/Http/AbstractApplication.php(120): TYPO3\CMS\Backend\Http\Application->handle(Object(TYPO3\CMS\Core\Http\ServerRequest))
#94 /home/example/html/public/typo3/index.php(24): TYPO3\CMS\Core\Http\AbstractApplication->run()
#95 /home/example/html/public/typo3/index.php(25): {closure}()
#96 {main}"}
~~~

</details>

**Comment by einpraegsam** [comment]
It's a pitty that in TYPO3 9 TypoScript is needed for the mapping configuration of the tables. And TypoScript was once made for frontend configuration and rendering. This is related to extbase and not to luxletter itself.

Possible solutions in your case:
* Update to TYPO3 10
* Copy the mapping configuration (see below) to the very first TypoScript template

```
config.tx_extbase {
    persistence {
        classes {
            In2code\Luxletter\Domain\Model\User {
                mapping {
                    tableName = fe_users
                }
            }
            In2code\Luxletter\Domain\Model\Usergroup {
                mapping {
                    tableName = fe_groups
                }
            }
        }
    }
}
```
